{
 "title": "RedisCluster-Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(redis_stats{}, node)"
   },
   {
    "name": "key",
    "label": "key",
    "query": "label_values(redis_stats{node=~\"$node\"}, key)"
   },
   { "name": "interval", "label": "interval", "query": "1m" }
  ]
 },
 "panels": [
  {
   "title": "Number of keys",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_stats{node=~\"$node\", key=\"db0_keys\"}",
     "legendFormat": "{{node}}-keys"
    }
   ]
  },
  {
   "title": "increase in number of keys",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(redis_stats{node=~\"$node\", key=\"db0_keys\"}[120s])/2)) by (node)",
     "legendFormat": "{{node}}-keys"
    }
   ]
  },
  {
   "title": "connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_stats{node=~\"$node\", key=\"connected_clients\"}",
     "legendFormat": "connections to {{node}}"
    }
   ]
  },
  {
   "title": "Persistent Keys in selected node",
   "type": "graph",
   "description": "Shows the keys which don't have any time to live set.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_stats{node=~\"$node\", key=\"db0_keys\"})  by (node) - sum(redis_stats{node=~\"$node\", key=\"db0_expires\"}) by (node)",
     "legendFormat": "persistent keys in {{node}}"
    }
   ]
  },
  {
   "title": "CPU usage selected node",
   "type": "graph",
   "description": "CPU usage for selected node. This should always be much less than the scrape interval. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(redis_stats{node=~\"$node\", key=~\"used_cpu_sys|used_cpu_sys_children|used_cpu_user|used_cpu_user_children\"}[120s])/2) by (node)",
     "legendFormat": "total-cpu-usage-for-{{node}}"
    }
   ]
  },
  {
   "title": "all types of cpu usage for selected nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(redis_stats{node=~\"$node\", key=~\"used_cpu_sys|used_cpu_sys_children|used_cpu_user|used_cpu_user_children\"}[120s])/2 > 0",
     "legendFormat": "{{node}}-{{key}}"
    }
   ]
  },
  {
   "title": "command cpu usage(all commands for selected node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(increase(redis_stats{node=~\"$node\", key=~\"cmdstat.*usec\"}[120s])/2) by (node, key)",
     "legendFormat": "{{node}}-{{key}}"
    }
   ]
  },
  {
   "title": "command cpu usage(selected node and cmdstat_* selected keys only)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(increase(redis_stats{node=~\"$node\", key=~\"$key\"}[120s])/2) by (node, key)",
     "legendFormat": "{{node}}-{{key}}"
    }
   ]
  },
  {
   "title": "Input bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(redis_stats{node=~\"$node\", key=\"total_net_input_bytes\"}[120s])/2",
     "legendFormat": "input to {{node}} in MB."
    }
   ]
  },
  {
   "title": "selected instance(s) and selected(cmdstat*calls) keys",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(redis_stats{node=~\"$node\", key=~\"$key\"}[120s])/2)) by (node, key)",
     "legendFormat": "{{key}} on {{node}}"
    }
   ]
  },
  {
   "title": "RSS  Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_stats{node=~\"$node\", key=\"used_memory_rss\"}",
     "legendFormat": "Memory RSS for {{node}}"
    }
   ]
  },
  {
   "title": "Ouput bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(redis_stats{node=~\"$node\", key=\"total_net_output_bytes\"}[120s])/2",
     "legendFormat": "Throughput - output to {{node}} in MB."
    }
   ]
  },
  {
   "title": "All Calls on selected instance(s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(redis_stats{node=~\"$node\", key=~\"cmdstat.*calls\"}[120s])/2)) by (node, key)",
     "legendFormat": "{{key}} on {{node}}"
    }
   ]
  },
  {
   "title": "Fragmentation Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_stats{node=~\"$node\", key=\"mem_fragmentation_ratio\"}",
     "legendFormat": "fragmentation ratio {{node}}"
    }
   ]
  },
  {
   "title": "selected key on selected instance(s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_stats{node=~\"$node\", key=~\"$key\"}",
     "legendFormat": "{{node}}-{{key}}"
    }
   ]
  },
  {
   "title": "increase in selected key(s) on selected instance(s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(redis_stats{node=~\"$node\", key=~\"$key\"}[120s])/2",
     "legendFormat": "increase in {{key}} in {{node}}"
    }
   ]
  },
  {
   "title": "Memory(all)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_stats{node=~\"$node\", key=~\"used_memory_rss|used_memory_peak|used_memory\"}",
     "legendFormat": "{{key}} {{node}}"
    }
   ]
  }
 ]
}